name: Publish on Azur 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt

      - name: Deploy to Azure App Service
        uses: azure/appservice-deploy@v2
        with:
          app-name: my-app
          app-service-plan: my-app-service-plan
          slot: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
